### ISSUE TITLE
python菜鸟求助报错

### ISSUE THREAD

**Issue by GOANDFUCKYOUSELF** [Nickydusk/AutoJR#3]
Traceback (most recent call last):
  File "C:\Users\Jonathan\Desktop\AutoJR-main\AutoJR.py", line 4, in <module>
    from strategy import *
  File "C:\Users\Jonathan\Desktop\AutoJR-main\strategy.py", line 5, in <module>
    from control import GameController
  File "C:\Users\Jonathan\Desktop\AutoJR-main\control.py", line 4, in <module>
    from airtest.core.api import start_app,stop_app,text,keyevent,auto_setup
ModuleNotFoundError: No module named 'airtest'

**Comment by huan-yp** [comment]
你没有装 airtest 库
`pip install airtest`
